/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.grafica;

import Exception.ComprobarDocumentoException;
import javax.swing.JOptionPane;
import laboratorio.Empleado;
import laboratorio.Empresa;

/**
 *
 * @author Marcelo
 */
public class EmpleadoAddVent extends javax.swing.JInternalFrame {
    Empresa emp;
    /**
     * Creates new form EmpleadoAddVent
     */
    public EmpleadoAddVent(Empresa emp) {
        this.emp = emp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbEmpleado = new javax.swing.JComboBox<>();
        labelNombre = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelDni = new javax.swing.JLabel();
        varNombre = new javax.swing.JTextField();
        varApellido = new javax.swing.JTextField();
        buttonGrabar = new javax.swing.JButton();
        labelEdad = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        varTitulo = new javax.swing.JTextField();
        radButtonHombre = new javax.swing.JRadioButton();
        radButtonMujer = new javax.swing.JRadioButton();
        labelDomicilio = new javax.swing.JLabel();
        varDomicilio = new javax.swing.JTextField();
        varEdad = new javax.swing.JFormattedTextField();
        varDni = new javax.swing.JFormattedTextField();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Seleccione Categoria:");

        cbEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrativo", "Enfermero", "Doctor", "Chofer" }));

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNombre.setText("Nombre:");

        labelApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelApellido.setText("Apellido:");

        labelDni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDni.setText("Nº Documento:");

        varNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        varNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNombreActionPerformed(evt);
            }
        });

        varApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonGrabar.setText("Grabar");
        buttonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGrabarActionPerformed(evt);
            }
        });

        labelEdad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelEdad.setText("Edad:");

        labelSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSexo.setText("Sexo:");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTitulo.setText("Titulo:");

        varTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        varTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varTituloActionPerformed(evt);
            }
        });

        radButtonHombre.setText("Hombre");
        radButtonHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButtonHombreActionPerformed(evt);
            }
        });

        radButtonMujer.setText("Mujer");
        radButtonMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButtonMujerActionPerformed(evt);
            }
        });

        labelDomicilio.setText("Domicilio:");

        varDomicilio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        varEdad.setFormatterFactory(new javax.swing.JFormattedTextField.AbstractFormatterFactory(){
            public javax.swing.JFormattedTextField.AbstractFormatter
            getFormatter(javax.swing.JFormattedTextField tf){
                try{
                    return new javax.swing.text.MaskFormatter("##");
                } catch (java.text.ParseException pe){
                    pe.printStackTrace(); 
                }
                return null;
            }
        });
        varEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        varEdad.setToolTipText("");
        varEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varEdadActionPerformed(evt);
            }
        });

        varDni.setFormatterFactory(new javax.swing.JFormattedTextField.AbstractFormatterFactory(){
            public javax.swing.JFormattedTextField.AbstractFormatter
            getFormatter(javax.swing.JFormattedTextField tf){
                try{
                    return new javax.swing.text.MaskFormatter("##.###.###");
                } catch (java.text.ParseException pe){
                    pe.printStackTrace(); 
                }
                return null;
            }
        });
        varDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelApellido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDni)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varDni, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelEdad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelSexo)
                                        .addGap(18, 18, 18)
                                        .addComponent(radButtonHombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(radButtonMujer))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDomicilio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonGrabar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(varNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido)
                    .addComponent(varApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDni)
                    .addComponent(varDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdad)
                    .addComponent(varEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexo)
                    .addComponent(radButtonHombre)
                    .addComponent(radButtonMujer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(varTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonGrabar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDomicilio)
                            .addComponent(varDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNombreActionPerformed

    private void buttonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGrabarActionPerformed
        try{
            String tipo = null;
            String sexo = null;
            if(radButtonHombre.isSelected()){
                sexo = "Hombre";
            }else{
                if(radButtonMujer.isSelected()){
                    sexo = "Mujer";
                }
            }
            int edad = Integer.parseInt(varEdad.getText());
            switch(cbEmpleado.getSelectedIndex()){
                case 0:
                    tipo = "Administrativo";
                    break;
                case 1:
                    tipo = "Enfermero";
                    break;
                case 2:
                    tipo = "Doctor";
                    break;
                case 3:
                    tipo = "Chofer";
                    break;
                default:
                    break;
            }
            emp.validarDni(varDni.getText());
            Empleado empleado = new Empleado(varNombre.getText(), varApellido.getText(), edad, sexo, varDni.getText(), varDomicilio.getText(), varTitulo.getText(), tipo);
            emp.addEmpleado(empleado);
            JOptionPane.showMessageDialog(this, "Empleado Agregado con Exito!!");
        } catch (ComprobarDocumentoException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage());
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ERROR: Faltaron ingresar datos");
        }
    }//GEN-LAST:event_buttonGrabarActionPerformed

    private void varTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varTituloActionPerformed

    private void varEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varEdadActionPerformed

    private void radButtonHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButtonHombreActionPerformed
        if(radButtonHombre.isSelected()){
            radButtonMujer.setSelected(false);
        }
    }//GEN-LAST:event_radButtonHombreActionPerformed

    private void radButtonMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButtonMujerActionPerformed
        if(radButtonMujer.isSelected()){
            radButtonHombre.setSelected(false);
        }
    }//GEN-LAST:event_radButtonMujerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGrabar;
    private javax.swing.JComboBox<String> cbEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JRadioButton radButtonHombre;
    private javax.swing.JRadioButton radButtonMujer;
    private javax.swing.JTextField varApellido;
    private javax.swing.JFormattedTextField varDni;
    private javax.swing.JTextField varDomicilio;
    private javax.swing.JFormattedTextField varEdad;
    private javax.swing.JTextField varNombre;
    private javax.swing.JTextField varTitulo;
    // End of variables declaration//GEN-END:variables
}
