/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.grafica;

import java.awt.Dimension;
import laboratorio.Empresa;
import javax.swing.JDesktopPane;

/**
 *
 * @author Marcelo
 */
public class Principal extends javax.swing.JFrame {
    private Empresa emp;
    /**
     * Creates new form Principal
     */
    public Principal() {
        this.emp = new Empresa();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAfiliado = new javax.swing.JMenu();
        menuItemAddAfil = new javax.swing.JMenuItem();
        menuItemAddFlia = new javax.swing.JMenuItem();
        menuItemVerAfil = new javax.swing.JMenuItem();
        menuItemEliminarAfil = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        menuItemAdms = new javax.swing.JMenuItem();
        menuItemEnf = new javax.swing.JMenuItem();
        menuItemDoc = new javax.swing.JMenuItem();
        menuItemChof = new javax.swing.JMenuItem();
        menuMovil = new javax.swing.JMenu();
        menuItemAdm2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        menuAfiliado.setText("Afiliado");

        menuItemAddAfil.setText("Agregar Afiliado");
        menuItemAddAfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddAfilActionPerformed(evt);
            }
        });
        menuAfiliado.add(menuItemAddAfil);

        menuItemAddFlia.setText("Agregar Familiar");
        menuItemAddFlia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddFliaActionPerformed(evt);
            }
        });
        menuAfiliado.add(menuItemAddFlia);

        menuItemVerAfil.setText("Ver Afiliados");
        menuItemVerAfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerAfilActionPerformed(evt);
            }
        });
        menuAfiliado.add(menuItemVerAfil);

        menuItemEliminarAfil.setText("Eliminar Afiliado");
        menuItemEliminarAfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarAfilActionPerformed(evt);
            }
        });
        menuAfiliado.add(menuItemEliminarAfil);

        jMenuBar1.add(menuAfiliado);

        menuEmpleados.setText("Empleados");

        menuItemAdms.setText("Administrativos");
        menuEmpleados.add(menuItemAdms);

        menuItemEnf.setText("Enfermeros");
        menuEmpleados.add(menuItemEnf);

        menuItemDoc.setText("Doctores");
        menuEmpleados.add(menuItemDoc);

        menuItemChof.setText("Choferes");
        menuEmpleados.add(menuItemChof);

        jMenuBar1.add(menuEmpleados);

        menuMovil.setText("Movil");

        menuItemAdm2.setText("Administrar");
        menuMovil.add(menuItemAdm2);

        jMenuBar1.add(menuMovil);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAddAfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddAfilActionPerformed
        AfiliadoVent ventana = new AfiliadoVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventana.show();
    }//GEN-LAST:event_menuItemAddAfilActionPerformed

    private void menuItemAddFliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddFliaActionPerformed
        FamiliarVent ventana = new FamiliarVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = ventana.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation(((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_menuItemAddFliaActionPerformed

    private void menuItemVerAfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerAfilActionPerformed
        VerAfiliaVent ventana = new VerAfiliaVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = ventana.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation(((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_menuItemVerAfilActionPerformed

    private void menuItemEliminarAfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarAfilActionPerformed
        EliminarAfiliadoVent ventana = new EliminarAfiliadoVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = ventana.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation(((desktopSize.width - FrameSize.height)/2), ((desktopSize.width - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_menuItemEliminarAfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAfiliado;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenuItem menuItemAddAfil;
    private javax.swing.JMenuItem menuItemAddFlia;
    private javax.swing.JMenuItem menuItemAdm2;
    private javax.swing.JMenuItem menuItemAdms;
    private javax.swing.JMenuItem menuItemChof;
    private javax.swing.JMenuItem menuItemDoc;
    private javax.swing.JMenuItem menuItemEliminarAfil;
    private javax.swing.JMenuItem menuItemEnf;
    private javax.swing.JMenuItem menuItemVerAfil;
    private javax.swing.JMenu menuMovil;
    // End of variables declaration//GEN-END:variables
}
