/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.grafica;

import java.awt.Dimension;
import laboratorio.Empresa;
import javax.swing.JDesktopPane;

/**
 *
 * @author Marcelo
 */
public class Principal extends javax.swing.JFrame {
    private Empresa emp;
    /**
     * Creates new form Principal
     */
    public Principal() {
        this.emp = new Empresa();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAfiliado = new javax.swing.JMenu();
        menuItemAddAfil = new javax.swing.JMenuItem();
        menuItemVerAfil = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        menuItemAdd = new javax.swing.JMenuItem();
        menuItemVer = new javax.swing.JMenuItem();
        menuMovil = new javax.swing.JMenu();
        menuItemAddMovil = new javax.swing.JMenuItem();
        menuItemVerMovil = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemPagoAdd = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAddSoli = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        menuAfiliado.setText("Afiliado");

        menuItemAddAfil.setText("Agregar Afiliado");
        menuItemAddAfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddAfilActionPerformed(evt);
            }
        });
        menuAfiliado.add(menuItemAddAfil);

        menuItemVerAfil.setText("Ver Afiliados");
        menuItemVerAfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerAfilActionPerformed(evt);
            }
        });
        menuAfiliado.add(menuItemVerAfil);

        jMenuBar1.add(menuAfiliado);

        menuEmpleados.setText("Empleados");

        menuItemAdd.setText("Agregar");
        menuItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemAdd);

        menuItemVer.setText("Ver");
        menuItemVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemVer);

        jMenuBar1.add(menuEmpleados);

        menuMovil.setText("Movil");
        menuMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMovilActionPerformed(evt);
            }
        });

        menuItemAddMovil.setText("Agregar");
        menuItemAddMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddMovilActionPerformed(evt);
            }
        });
        menuMovil.add(menuItemAddMovil);

        menuItemVerMovil.setText("Ver");
        menuItemVerMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerMovilActionPerformed(evt);
            }
        });
        menuMovil.add(menuItemVerMovil);

        jMenuBar1.add(menuMovil);

        jMenu1.setText("Registro Pago");

        menuItemPagoAdd.setText("Agregar");
        menuItemPagoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPagoAddActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemPagoAdd);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Solicitudes");

        menuItemAddSoli.setText("Agregar");
        menuItemAddSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddSoliActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAddSoli);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Resultados");

        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAddAfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddAfilActionPerformed
        AfiliadoVent ventana = new AfiliadoVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventana.show();
    }//GEN-LAST:event_menuItemAddAfilActionPerformed

    private void menuItemVerAfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerAfilActionPerformed
        VerRemoveAfiliadoVent ventana = new VerRemoveAfiliadoVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation(((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_menuItemVerAfilActionPerformed

    private void menuItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddActionPerformed
        EmpleadoAddVent ventana = new EmpleadoAddVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_menuItemAddActionPerformed

    private void menuItemVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerActionPerformed
        VerRemoveEmpleadoVent ventana = new VerRemoveEmpleadoVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_menuItemVerActionPerformed

    private void menuItemAddMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddMovilActionPerformed
        MovilVent ventana = new MovilVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_menuItemAddMovilActionPerformed

    private void menuItemVerMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerMovilActionPerformed
        VerRemoveMovilVent ventana = new VerRemoveMovilVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
        
    }//GEN-LAST:event_menuItemVerMovilActionPerformed

    private void menuItemPagoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPagoAddActionPerformed
        PagoVent ventana = new PagoVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_menuItemPagoAddActionPerformed

    private void menuItemAddSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddSoliActionPerformed
        SolicitudVent ventana = new SolicitudVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_menuItemAddSoliActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ResultadoVent ventana = new ResultadoVent(emp);
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMovilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAfiliado;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenuItem menuItemAdd;
    private javax.swing.JMenuItem menuItemAddAfil;
    private javax.swing.JMenuItem menuItemAddMovil;
    private javax.swing.JMenuItem menuItemAddSoli;
    private javax.swing.JMenuItem menuItemPagoAdd;
    private javax.swing.JMenuItem menuItemVer;
    private javax.swing.JMenuItem menuItemVerAfil;
    private javax.swing.JMenuItem menuItemVerMovil;
    private javax.swing.JMenu menuMovil;
    // End of variables declaration//GEN-END:variables
}
