/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.grafica;

import Exception.ComprobarAfiliadoException;
import Exception.CustomException;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import laboratorio.Afiliado;
import laboratorio.Persona;
import laboratorio.Empresa;

/**
 *
 * @author Marcelo
 */
public class VerRemoveAfiliadoVent extends javax.swing.JInternalFrame {
    public Empresa emp;
    /**
     * Creates new form VerAfiliaVent
     */
    public VerRemoveAfiliadoVent(Empresa emp) {
        this.emp = emp;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        labelDomicilio3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelNombre3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelApellido3 = new javax.swing.JLabel();
        varNumAfil = new javax.swing.JTextField();
        labelDni3 = new javax.swing.JLabel();
        labelEdad3 = new javax.swing.JLabel();
        labelSexo3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonBuscar = new javax.swing.JButton();
        buttonGrupoFlia = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonAddFlia = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        labelDomicilio3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nº Documento:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Edad:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Sexo:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Domicilio:");

        labelNombre3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Nº Afiliado:");

        labelApellido3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelDni3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelEdad3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelSexo3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Apellido:");

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        buttonGrupoFlia.setText("Ver Grupo Familiar");
        buttonGrupoFlia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGrupoFliaActionPerformed(evt);
            }
        });

        jButton3.setText("Ver Historia Clinica");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonAddFlia.setText("Agregar Familiar");
        buttonAddFlia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddFliaActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        desktopPane.setLayer(labelDomicilio3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(labelNombre3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(labelApellido3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(varNumAfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(labelDni3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(labelEdad3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(labelSexo3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonGrupoFlia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonAddFlia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAddFlia)
                        .addGap(18, 18, 18)
                        .addComponent(buttonGrupoFlia)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDomicilio3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSexo3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEdad3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDni3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(79, 298, Short.MAX_VALUE))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(172, 206, Short.MAX_VALUE)
                        .addComponent(buttonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonEliminar)
                        .addGap(35, 35, 35))))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(varNumAfil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(276, Short.MAX_VALUE)))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBuscar)
                    .addComponent(buttonEliminar)
                    .addComponent(buttonModificar))
                .addGap(11, 11, 11)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(labelApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(labelDni3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(labelEdad3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(labelSexo3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDomicilio3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddFlia)
                    .addComponent(buttonGrupoFlia)
                    .addComponent(jButton3))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desktopPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(varNumAfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(377, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        
        try{
        int numAf = Integer.parseInt(varNumAfil.getText());
        emp.comprobarAfiliado(numAf);
        Persona afi = emp.buscarAf(numAf);
        
            labelNombre3.setText(afi.getNombre());
            labelApellido3.setText(afi.getApellido());
            labelDni3.setText(afi.getDni());
            String edad = String.valueOf(afi.getEdad());
            labelEdad3.setText(edad);
            labelSexo3.setText(afi.getSexo());
            labelDomicilio3.setText(afi.getDomicilio());
        
        }catch (ComprobarAfiliadoException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }catch (NumberFormatException e){
           
            JOptionPane.showMessageDialog(null,"Error: Campo vacío o el formato que intenta ingresar es incorrecto");
        }catch (NullPointerException e){
            labelNombre3.setText("");
            labelApellido3.setText("");
            labelDni3.setText("");
            String edad = String.valueOf("");
            labelEdad3.setText("");
            labelSexo3.setText("");
            labelDomicilio3.setText("");
            JOptionPane.showMessageDialog(null,"Error: No existe Afiliado con el número ingresado");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+ e.getMessage());
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonGrupoFliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGrupoFliaActionPerformed
        try{
            int numAf = Integer.parseInt(varNumAfil.getText());
            Persona afi = emp.buscarAf(numAf);
            if(!(afi == null)){
                VerRemoveFamiliarVent ventana = new VerRemoveFamiliarVent(emp, varNumAfil.getText());
                desktopPane.add(ventana);
                Dimension desktopSize = desktopPane.getSize();
                Dimension FrameSize = ventana.getSize();
                ventana.setLocation(((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
                ventana.show();
            }else{
                JOptionPane.showMessageDialog(null,"ERROR: Primero debe BUSCAR el Afiliado");
            }
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Error: No ingreso ningún dato, recuerdo que primero debe BUSCAR el Afiliado");
        }
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(null,"Error: Primero debe buscar el Afiliado");
        }
    }//GEN-LAST:event_buttonGrupoFliaActionPerformed

    private void buttonAddFliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddFliaActionPerformed
        try{
        
            int numAf = Integer.parseInt(varNumAfil.getText());
            Persona afi = emp.buscarAf(numAf);
            if(!(afi == null)){
                FamiliarVent ventana = new FamiliarVent(emp, varNumAfil.getText());
                desktopPane.add(ventana);
                Dimension desktopSize = desktopPane.getSize();
                Dimension FrameSize = ventana.getSize();
                ventana.setLocation(((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
                ventana.show();
            }else{
                JOptionPane.showMessageDialog(null,"ERROR: Primero debe BUSCAR el Afiliado");
            }
        }
        catch (NumberFormatException e){
           
            JOptionPane.showMessageDialog(null,"Error: No ingreso ningún dato, recuerdo que primero debe BUSCAR el Afiliado");
        }
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(null,"Error: Primero debe buscar el Afiliado");
        }
    }//GEN-LAST:event_buttonAddFliaActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        try{
            int numAf = Integer.parseInt(varNumAfil.getText());

            if(emp.eliminarAf(numAf)){
                System.out.println("Afiliado Eliminado con Exito");
            }else{
                JOptionPane.showMessageDialog(null,"ERROR: Primero debe BUSCAR el Afiliado");
            }
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Error: No ingreso ningún dato, recuerdo que primero debe BUSCAR el Afiliado");
        }
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(null,"Error: Primero debe buscar el Afiliado");
        }
        
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        try{
        ModificarAfiliado ventana = new ModificarAfiliado(emp, varNumAfil.getText());
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
        }catch (NumberFormatException e){
           
            JOptionPane.showMessageDialog(null,"Error: No ingreso ningún dato, recuerdo que primero debe buscar el Afiliado");
        }
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(null,"Error: Primero debe buscar el Afiliado");
        }
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            HistoriaClinicaVent ventana = new HistoriaClinicaVent(emp, varNumAfil.getText());
            desktopPane.add(ventana);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = ventana.getSize();
            ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
            ventana.show();
        }catch (NumberFormatException e){
           
            JOptionPane.showMessageDialog(null,"Error: No ingreso ningún dato, recuerdo que primero debe BUSCAR el Afiliado");
        }
        catch (NullPointerException e){
            JOptionPane.showMessageDialog(null,"Error: Primero debe BUSCAR el Afiliado");
        }catch(CustomException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddFlia;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonGrupoFlia;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelApellido3;
    private javax.swing.JLabel labelDni3;
    private javax.swing.JLabel labelDomicilio3;
    private javax.swing.JLabel labelEdad3;
    private javax.swing.JLabel labelNombre3;
    private javax.swing.JLabel labelSexo3;
    private javax.swing.JTextField varNumAfil;
    // End of variables declaration//GEN-END:variables
}
