/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.grafica;

import Exception.CustomException;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import laboratorio.Empleado;
import laboratorio.Empresa;

/**
 *
 * @author Marcelo
 */
public class VerRemoveEmpleadoVent extends javax.swing.JInternalFrame {

    Empresa emp;
    /**
     * Creates new form EliminarEmpleadoVent
     */
    public VerRemoveEmpleadoVent(Empresa emp) {
        this.emp = emp;
        initComponents();
        armarList();
       bloquear();
    }
    
    public void bloquear(){
        buttonModificar.setEnabled(false);
        buttonEliminar.setEnabled(false);
    }
    public void desbloquear(){
        buttonModificar.setEnabled(true);
        buttonEliminar.setEnabled(true);
    }
    public void armarList(){
        for(int i = 0; i < emp.getEmpleado().size(); i++){
            listEmpleado.add(emp.getEmpleado().get(i).getNombre() + " " + emp.getEmpleado().get(i).getApellido());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        listEmpleado = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        buttonModificar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonActualizar = new javax.swing.JButton();

        setClosable(true);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        listEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEmpleadoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(textPane);

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre de Empleado:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Datos del Empleado:");

        buttonActualizar.setText("Actualizar");
        buttonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarActionPerformed(evt);
            }
        });

        desktopPane.setLayer(listEmpleado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(buttonActualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(buttonModificar)
                                .addGap(18, 18, 18)
                                .addComponent(buttonEliminar))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(listEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonModificar)
                    .addComponent(buttonEliminar)
                    .addComponent(buttonActualizar))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        try{
            emp.eliminarEmp(emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getDni());
            JOptionPane.showMessageDialog(this, "Empleado eliminado con Exito!!");
            textPane.setText("");
            listEmpleado.clear();
            armarList();
            bloquear();
        }catch(CustomException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void listEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEmpleadoActionPerformed
        desbloquear();
        String edad = String.valueOf(emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getEdad());
        textPane.setText("Categoria: " + emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getCategoria() + "\nNombre: " + emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getNombre() + "\nApellido: " + emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getApellido() + "\nNº Documento: " + emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getDni() + "\nEdad: " + edad + "\nSexo: " + emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getSexo() + "\nTitulo: " + emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getTitulo()+ "\nDomicilio: " + emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getDomicilio());
    }//GEN-LAST:event_listEmpleadoActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        ModificarEmpleado ventana = new ModificarEmpleado(emp, emp.getEmpleado().get(listEmpleado.getSelectedIndex()).getDni());
        desktopPane.add(ventana);
        Dimension desktopSize = desktopPane.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation (((desktopSize.width - FrameSize.width)/2), ((desktopSize.height - FrameSize.height)/2));
        ventana.show();
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarActionPerformed
        listEmpleado.clear();
        textPane.setText("");
        armarList();
        bloquear();
    }//GEN-LAST:event_buttonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonActualizar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.List listEmpleado;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
